### PR TITLE
Designed Home page and added Course Tag helper widget

### PR DESCRIPTION
**Pull request by SakshhamTheCoder**
# Changes for pull request with respect to #2
- Designed the full home page for the app following design guidelines present on Figma design provided, including every small details such as same colour scheme and layout
- Added [course_tags.dart](https://github.com/SakshhamTheCoder/dsc-learn-app/blob/home-page/lib/src/ui/widgets/course_tags.dart/) file which includes helper widget for Course tags (eg. Most popular, Trending etc) that is showed underneath course selection widget
- Changed System UI Status Bar overlay to transparent for seamless app experience

Screenshot-
Screenshot 2023-09-23 232806

# TODO
- Dynamic username on title bar - added by putting current logged in user's name
- Course related card images on course selection cards - currently using a random image from internet, change to course related image
- Add button and cards onPressed callback functionalities - currently using a null callback, doing nothing, change to do real actions
- Make search bar working - currently just a text field with no text controller, add search functionalities to it

# Credits (Thank you)
- Made by [Sakshham Bhagat](https://github.com/SakshhamTheCoder/)
  -  1st Year Thapar Student
  -  Branch COE
  -  Application number 104697
  - 2 years experience in Flutter App dev and having 5 year experience in programming overall

### CODE REVIEW

**Comment by AyushKrSingh000** [comment]
Will review this and let you know by tomorrow

**Comment by SakshhamTheCoder** [comment]
Please provide an update at your earliest convenience

**Comment by AyushKrSingh000** [comment]
# Please Fix the following issues:

## 1. Use ListView.builder() for categories as well as for popular course.
## 2. Fix the Padding issue in popular courses(see the below image)
ss<hr>
## 3. Use CachedNetworkImage  for network images [use this package](https://pub.dev/packages/cached_network_image)

## 4. Fix the desgin of popular course card (size is small) and padding of rating and bookmark icon
ss<hr>

## 5. Fix the padding issues(take accurate padding from figma link)
ss<hr>


## 6. Fix the ongoing course  card design it's not matching with design
ss<hr>


## 7. Also try to make separate file for each component of the page so that it can be easily maintainable

# If you need any help just comment here.

**Comment by SakshhamTheCoder** [comment]
Alright I am on it. Will get back to you ASAP.

**Comment by SakshhamTheCoder** [comment]
Did everything except the point no.2 (card padding fix on the right). Cant seem to find a way to remove padding from a single ListView. If I remove padding from Scaffold body itself, the whole page is going to get 0 padding which is bad. Any help is appreciable

**Comment by SKULLCRUS** [comment]
Kindly push the latest code,so that we can assist you with the issues if any.

**Comment by SakshhamTheCoder** [comment]
Pushed latest code to codebase. I currently have two problems
- Category button not having even spacing between them
- Popular course card not having no padding on right (Padding not working as intended)

I have commented the problems at the respective lines in home_page.dart. You can check from there.

**Comment by AyushKrSingh000** [comment]
@SakshhamTheCoder  we will review it and fix the code and will let you know

**Comment by SakshhamTheCoder** [comment]
Any updates on this?

**Comment by SKULLCRUS** [comment]
For now I am merging your PR to feature/home-page branch.All the required changes will be done in the same branch,you can visit the changes that will be done later.

**Comment by SKULLCRUS** [comment]
Please mail  your personal and contact details  at ayushkumarsingh0708@gmail.com so as to consider your application for recruitment.

**Comment by SakshhamTheCoder** [comment]
Thank you so much. Will do it right now

**Pull request merged**
